name: cozy_mopail_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  intl: ^0.19.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  date_picker_timeline: ^1.2.6
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
  
  # fonts:
  #   - family: Dubai
  #     fonts:
  #       - asset: assets/fonts/Dubai-Regular.ttf
  #       - asset: assets/fonts/Dubai-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Dubai-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Dubai-Light.ttf
  #         weight: 300

