version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cozy-postgres
    environment:
      POSTGRES_DB: cozy_db
      POSTGRES_USER: cozy_user
      POSTGRES_PASSWORD: cozy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cozy-network
    restart: unless-stopped

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: cozy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cozy-network
    restart: unless-stopped

  # Cozy Application
  cozy-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cozy-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://cozy_user:cozy_password@postgres:5432/cozy_db
      - DATABASE_DIRECT_URL=postgresql://cozy_user:cozy_password@postgres:5432/cozy_db
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      # Add other environment variables as needed
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - cozy-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: cozy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - cozy-app
    networks:
      - cozy-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:


networks:
  cozy-network:
    driver: bridge

